# Your Website Title
title: Melvin Ch'ng

# Your Website URL
url: 'http://your-url.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Ing. Yam Espinosa Noe Ezequiel
tagline: Software Developer, IoT, Reverse Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: ingeniero en sistemas en proceso
description_tiny: ' Deportista | programador  '
email: you.email.email@gmail.com
website: melvinchng.github.io # do not add http://
linkedin: realmelvinchng
github: melvinchng
twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
