# Your Website Title
title: Noe Yam

# Your Website URL
url: 'http://your-url.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Ing. Noe Yam
tagline: Software Developer and Reverse Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: ingeniero en sistemas en proceso
description_tiny: ' Deportista | programador  '
email: power2000.ny@gmail.com
#website: melvinchng.github.io # do not add http://
linkedin: i don't have :c
github: NoeYam
twitter: '@ing.Noeyam2'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
